# Generated by Django 5.2.6 on 2025-09-11 13:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('scheme_name', models.CharField(help_text='Official name of the scheme', max_length=500, validators=[django.core.validators.MinLengthValidator(3)])),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of scheme name', max_length=200, unique=True)),
                ('details', models.TextField(blank=True, help_text='Detailed description of the scheme', null=True)),
                ('benefits', models.TextField(blank=True, help_text='Benefits provided by the scheme', null=True)),
                ('eligibility', models.TextField(blank=True, help_text='Eligibility criteria for the scheme', null=True)),
                ('application', models.TextField(blank=True, help_text='Application process and procedure', null=True)),
                ('documents', models.TextField(blank=True, help_text='Required documents for application', null=True)),
                ('level', models.CharField(choices=[('central', 'Central Government'), ('state', 'State Government'), ('district', 'District Level'), ('block', 'Block Level'), ('panchayat', 'Panchayat Level')], default='central', help_text='Government level offering this scheme', max_length=20)),
                ('scheme_category', models.CharField(choices=[('agriculture', 'Agriculture'), ('education', 'Education'), ('healthcare', 'Healthcare'), ('employment', 'Employment'), ('women_child', 'Women & Child Development'), ('rural_development', 'Rural Development'), ('housing', 'Housing'), ('financial_inclusion', 'Financial Inclusion'), ('disability', 'Disability Welfare'), ('elderly', 'Elderly Welfare'), ('minority', 'Minority Affairs'), ('tribal', 'Tribal Affairs'), ('skill_development', 'Skill Development'), ('environment', 'Environment'), ('transport', 'Transport'), ('social_welfare', 'Social Welfare'), ('other', 'Other')], default='other', help_text='Category of the scheme', max_length=30)),
                ('state', models.CharField(blank=True, help_text='Specific state (for state-level schemes)', max_length=100, null=True)),
                ('ministry_department', models.CharField(blank=True, help_text='Ministry or department managing the scheme', max_length=200, null=True)),
                ('launch_date', models.DateField(blank=True, help_text='Date when scheme was launched', null=True)),
                ('website_url', models.URLField(blank=True, help_text='Official website for the scheme', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the scheme is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_keywords', models.TextField(blank=True, help_text='Additional keywords for search optimization')),
            ],
            options={
                'ordering': ['scheme_name'],
                'indexes': [models.Index(fields=['level'], name='schemes_sch_level_05b049_idx'), models.Index(fields=['scheme_category'], name='schemes_sch_scheme__293bda_idx'), models.Index(fields=['state'], name='schemes_sch_state_7cd30a_idx'), models.Index(fields=['is_active'], name='schemes_sch_is_acti_0f8bf3_idx'), models.Index(fields=['-created_at'], name='schemes_sch_created_3cd28e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SchemeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('identity', 'Identity Proof'), ('address', 'Address Proof'), ('income', 'Income Proof'), ('age', 'Age Proof'), ('education', 'Education Certificate'), ('employment', 'Employment Proof'), ('medical', 'Medical Certificate'), ('other', 'Other')], default='other', max_length=50)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='schemes.scheme')),
            ],
            options={
                'unique_together': {('scheme', 'document_name')},
            },
        ),
    ]
